// <auto-generated />
using System;
using ManufacturerExtraction.Api.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ManufacturerExtraction.Api.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260806144707_AddCumulativePeriodColumns")]
    partial class AddCumulativePeriodColumns
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ManufacturerExtraction.Api.Models.AnalyticsExtraction", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("AnalyticsJson")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("DocumentId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("SchemaVersion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("DocumentId")
                        .IsUnique();

                    b.ToTable("AnalyticsExtractions");
                });

            modelBuilder.Entity("ManufacturerExtraction.Api.Models.Document", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("AnalysisCompletedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("BlobUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ContentUnderstandingJobId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CustomInstructions")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("CustomerCount")
                        .HasColumnType("int");

                    b.Property<string>("ErrorMessage")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("FileSizeBytes")
                        .HasColumnType("bigint");

                    b.Property<string>("FileType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("HasWarnings")
                        .HasColumnType("bit");

                    b.Property<bool>("IsCumulative")
                        .HasColumnType("bit");

                    b.Property<int?>("LineCount")
                        .HasColumnType("int");

                    b.Property<string>("Manufacturer")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("MonthlyCommission")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int?>("MonthlyLineCount")
                        .HasColumnType("int");

                    b.Property<decimal?>("MonthlyNetSales")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("OriginalFileName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PeriodMonth")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PeriodYear")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProcessingStatus")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<double>("ProgressPct")
                        .HasColumnType("float");

                    b.Property<decimal?>("TotalCommission")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("TotalNetSales")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("UploadDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("ProcessingStatus");

                    b.HasIndex("UploadDate");

                    b.ToTable("Documents");
                });

            modelBuilder.Entity("ManufacturerExtraction.Api.Models.RawExtraction", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("DocumentId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("RawJson")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("DocumentId")
                        .IsUnique();

                    b.ToTable("RawExtractions");
                });

            modelBuilder.Entity("ManufacturerExtraction.Api.Models.AnalyticsExtraction", b =>
                {
                    b.HasOne("ManufacturerExtraction.Api.Models.Document", "Document")
                        .WithOne("AnalyticsExtraction")
                        .HasForeignKey("ManufacturerExtraction.Api.Models.AnalyticsExtraction", "DocumentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Document");
                });

            modelBuilder.Entity("ManufacturerExtraction.Api.Models.RawExtraction", b =>
                {
                    b.HasOne("ManufacturerExtraction.Api.Models.Document", "Document")
                        .WithOne("RawExtraction")
                        .HasForeignKey("ManufacturerExtraction.Api.Models.RawExtraction", "DocumentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Document");
                });

            modelBuilder.Entity("ManufacturerExtraction.Api.Models.Document", b =>
                {
                    b.Navigation("AnalyticsExtraction");

                    b.Navigation("RawExtraction");
                });
#pragma warning restore 612, 618
        }
    }
}
